### ISSUE TITLE
Does not work with node v6.5

### ISSUE THREAD

**Issue by bishtawi** [gyson/koa-convert#6]
Hi,
I have a webapp that I built using the koa v2 framework. I use koa-convert, koa-generic-session and koa-redis to store user sessions in my redis instance. Since upgrading to node v6.5, my webapp fails with the following stacktrace:

```
TypeError: Cannot read property 'done' of undefined
      at next (/Users/dev/work/node_modules/co/index.js:98:14)
      at onFulfilled (/Users/dev/work/node_modules/co/index.js:69:7)
      at /Users/Stephen/dev/work/node_modules/co/index.js:54:5
      at Object.co (/Users/dev/work/node_modules/co/index.js:50:10)
      at next (/Users/dev/work/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/dev/work/node_modules/co/index.js:69:7)
```

It worked fine with node v6.4. The stacktrace doesnt go past co, but through trial and error, I deleted a lot of third party libs and middleware and narrowed it down to this block of code:

```
app.use(convert(session({
  key: 'session',
  errorHandler(err, type, ctx) {
    console.error(err, type)
  },
  store: redisStore({ url: config.redis.url })
})))
```

which can be reduced to `app.use(convert(session()))` and still trigger the same bug.

I do not use the convert lib anywhere else in the app so I cannot quickly test to see if the issue is specifically in the convert or session lib.

**Comment by bishtawi** [comment]
Adding @targos

**Comment by gyson** [comment]
Which version do you use ? (for koa, koa-convert & koa-generic-session)

**Comment by bishtawi** [comment]
Ah, good question. I should have mentioned it in my original post.

Koa: 2.0.0
Koa-convert: 1.2.0
Koa-generic-session: 1.11.3

**Comment by bishtawi** [comment]
Did some more testing. Its due to the `--harmony` flag that I am including when running node.

Smallest failing test case:

```
const Koa = require('koa')
const convert = require('koa-convert')
const session = require('koa-generic-session')

const app = new Koa()
app.use(convert(session()))

app.listen(3000)
```

Running `node --harmony index.js` then hitting localhost:3000 in a webbrowser returns a 500 instead of the expected 404.

Running without the harmony flag works as expected.

**Comment by gyson** [comment]
Thanks for the detailed report. The stacktrace looks a little bit strange. It basically says that calling `generator.next()` will return `undefined` instead of `{ done, result }` protocol. I think it's more likely to be a nodejs/V8 bug.

Also, `--harmony` flag is usually not suitable for production.

**Comment by targos** [comment]
This is a bug in V8 with tail call optimization. The `--harmony-tailcalls` flag (implied by `--harmony`) is enough to trigger it. It will probably not be fixed in Node.js because the feature is not considered stable in V8 5.1.
I suggest you drop the `--harmony` flag and if you really need one of the features that it activates, enable it directly. Here is the list: https://github.com/nodejs/node/blob/v6.5.0/deps/v8/src/flag-definitions.h#L211-L216

**Comment by bishtawi** [comment]
Thanks everyone. I removed the harmony flag and my app works fine. Looks like the only reason why I had it was due to needing it back in the old node 0.12.x to get generators, arrow functions, promises, block scoping, etc.

**Comment by bishtawi** [comment]
Closing as its a bug in V8
